### ISSUE TITLE
After logging in, it is up to 404 Page Not Found

### ISSUE THREAD

**Issue by vb4win** [Akshat4112/SchoolErp#15]
I downloaded it to my server that uses AppServ.After logging in, it is an error to 404 Page Not Found. Please provide instructions. This is address on display "http://localhost/schoolerp/home/admin_login"

**Comment by vb4win** [comment]
This is address on display http://localhost/schoolerp/home/admin_login

**Comment by Akshat4112** [comment]
Please Change the directory name in the .htaccess file in root directory according to your directory name.
